# Generated by Django 5.x for DeltaJanebi homepage category source cloning.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_productsourceoffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCategoryShowcase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="دسته‌بندی محصولات", max_length=160)),
                ("subtitle", models.CharField(blank=True, max_length=240)),
                ("source_url", models.URLField(blank=True, max_length=4096)),
                ("enabled", models.BooleanField(default=False)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepage_category_showcases", to="shop.sourcesite")),
            ],
            options={
                "verbose_name": "چیدمان دسته‌بندی صفحه اصلی",
                "verbose_name_plural": "چیدمان دسته‌بندی صفحه اصلی",
            },
        ),
        migrations.CreateModel(
            name="HomeCategoryTile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160)),
                ("image_url", models.URLField(blank=True, max_length=4096)),
                ("source_category_url", models.URLField(blank=True, max_length=4096)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepage_tiles", to="shop.category")),
                ("showcase", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tiles", to="shop.homecategoryshowcase")),
                ("source_site", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="homepage_category_tiles", to="shop.sourcesite")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="homecategorytile",
            index=models.Index(fields=["showcase", "is_active", "order"], name="shop_homecat_show_idx"),
        ),
    ]
